// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBanking.Domain.Entities;

namespace OnlineBanking.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210907232113_Created-Database")]
    partial class CreatedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBanking.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(38,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = 211979756,
                            Balance = 23456782340m,
                            CreatedAt = new DateTime(2021, 9, 7, 23, 21, 11, 653, DateTimeKind.Utc).AddTicks(1519),
                            CreatedBy = "Dara",
                            CustomerId = 1,
                            UpdatedAt = new DateTime(2021, 9, 7, 23, 21, 11, 653, DateTimeKind.Utc).AddTicks(2115),
                            UpdatedBy = "Dara"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = 317092802,
                            Balance = 23456782340m,
                            CreatedAt = new DateTime(2021, 9, 7, 23, 21, 11, 653, DateTimeKind.Utc).AddTicks(3808),
                            CreatedBy = "Obinna",
                            CustomerId = 2,
                            UpdatedAt = new DateTime(2021, 9, 7, 23, 21, 11, 653, DateTimeKind.Utc).AddTicks(3836),
                            UpdatedBy = "Obinna"
                        });
                });

            modelBuilder.Entity("OnlineBanking.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 1,
                            Birthday = new DateTime(2000, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dara@domain.com",
                            FirstName = "Dara",
                            Gender = 1,
                            LastName = "Success"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 1,
                            Birthday = new DateTime(2004, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "obinna@gmail.com",
                            FirstName = "Obinna",
                            Gender = 0,
                            LastName = "Achara"
                        });
                });

            modelBuilder.Entity("OnlineBanking.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
